spring.application.name=ManualBalancedDB

# spring.data.mongodb.uri=mongodb+srv://abhijeett55:87654321@podium.x9devgj.mongodb.net/podium?retryWrites=true&w=majority


spring.data.mongodb.uri=mongodb+srv://abhijeetavi25:8765432uth1@auth.oty1qyu.mongodb.net/auth?retryWrites=true&w=majority&appName=Auth
spring.data.mongodb.database=auth
server.port=8081

logging.level.org.springframework.security=DEBUG
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
jwt.secret=mySecretKeyForJWTGenerationChangeThisInProduction
jwt.expiration=86400000
