spring.application.name=Vaultic_auth


spring.data.mongodb.uri=mongodb+srv://vaultic:Avi123456789@vaultic.dmwqlan.mongodb.net/vaultic?retryWrites=true&w=majority&appName=vaultic
spring.data.mongodb.database=vaultic
server.port=8081

logging.level.org.springframework.security=DEBUG

jwt.secret=mySecretKeyForJWTGenerationChangeThisInProduction
jwt.expiration=86400000
