spring.application.name=Vaultic_auth

spring.data.mongodb.uri=${MONGODB_URI}

server.port=${PORT:8081}
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.security=DEBUG

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000